using System;
using System.Collections.Generic;
using System.Text;

namespace WzComparerR2
{
    public enum GearPropType
    {
        //普通装备属性
        incSTR = 1,
        incSTRr,
        incDEX,
        incDEXr,
        incINT,
        incINTr,
        incLUK,
        incLUKr,
        incAllStat,
        incMHP,
        incMHPr,
        incMMP,
        incMMPr,
        incPAD,
        incMAD,
        incPDD,
        incMDD,
        incACC,
        incEVA,
        incSpeed,
        incJump,
        incCraft,
        knockback,
        incPVPDamage,
        bdR,
        incBDR,
        imdR,
        incIMDR,
        damR,

        //潜能属性
        incPADr = 100,
        incMADr,
        incPDDr,
        incMDDr,
        incACCr,
        incEVAr,
        incCr,
        incDAMr,
        RecoveryHP,
        RecoveryMP,
        face,
        prop,
        time,
        HP,
        MP,
        attackType,
        ignoreTargetDEF,
        ignoreDAM,
        ignoreDAMr,
        DAMreflect,
        mpconReduce,
        mpRestore,
        incMesoProp,
        incRewardProp,
        incAllskill,
        RecoveryUP,
        boss,
        level,
        incTerR,
        reduceCooltime,
        incCriticaldamageMax,
        incCriticaldamageMin,
        @sealed,
        incSTRlv,
        incDEXlv,
        incINTlv,
        incLUKlv,

        Option,
        OptionToMob,
        activeSkill,
        //特殊装备属性
        attackSpeed = 200,
        tuc,
        setItemID,
        durability,
        reqCraft,
        cash,
        reduceReq,

        //技能特有属性
        mastery = 300,
        criticaldamageMin,
        criticaldamageMax,
        epad,
        emad,
        epdd,
        emdd,
        emhp,
        emmp,
        smartpad,
        smartacc,
        smarteva,

        //装备特有属性
        reqLevel = 1000,
        reqSTR,
        reqDEX,
        reqINT,
        reqLUK,
        reqJob,
        reqPOP,
        reqSpecJob,
        reqWeekDay, //要求日子
        grade,

        only = 1100,
        //notSale,
        //dropBlock,
        tradeBlock,
        accountSharable,
        onlyEquip,
        tradeAvailable,
        equipTradeBlock,
        sharableOnce,
        notExtend,
        epicItem,
        charismaEXP,
        senseEXP,
        insightEXP,
        willEXP,
        craftEXP,
        charmEXP,
        accountShareTag,
        noPotential,
        fixedPotential,
        timeLimited,
        specialGrade,
        fixedGrade,
        unchangeable,
        superiorEqp,
        incPQEXPr,
        limitBreak,
        nActivatedSocket,
        jokerToSetItem,
        
    }
}
